### ISSUE TITLE
Create schedule data 

### ISSUE THREAD

**Issue by bhansa** [HydPy/hydpyconf2019#1]
Currently the schedule data is not dynamic and coming from DOM, we need to keep data under `_data/schedule.yml` and pull it from there.

Reference: [How to use data files in jekyll](https://jekyllrb.com/docs/datafiles/)

**Comment by ananyo2012** [comment]
@bhansa Can you work on this ? Also we have 2 parallel tracks so we need to update the layout accordingly.

**Comment by bhansa** [comment]
I will try to put some outline for the schedule.
