### ISSUE TITLE
Publish selected talks on the website along with Abstract

### ISSUE THREAD

**Issue by inovizz** [HydPy/hydpyconf2019#105]

**Comment by ananyo2012** [comment]
@inovizz Can we link to the abstract in Papercall instead of putting the whole abstract in website ?

**Comment by inovizz** [comment]
Papercall is private I believe.

**Comment by ananyo2012** [comment]
@inovizz This is done. Since all talks don't have Abstract let's skip the abstracts for Talks.

**Comment by inovizz** [comment]
Can you do one thing - Do the setup/code and mention "To Be Added". I'll get details and add data into yml file.

**Comment by inovizz** [comment]
We need to show abstract to participants - I'll get that. It will be important on the day of the conference. As it will help people choose a talk.

**Comment by ananyo2012** [comment]
Ah setup is already there. You just need to Add the description to Talk section and it will show up.

**Comment by inovizz** [comment]
What about pictures and Social links. Those are also setup right?

**Comment by ananyo2012** [comment]
For speakers there are no template blocks. You need to add the full data
blocks. Other things are setup.

**Comment by ananyo2012** [comment]
@GoelJatin Can you take up this task of updating Conference speaker and talk details ?

**Comment by GoelJatin** [comment]
@ananyo2012 , can you provide me with the document which has the speaker and talk details?

**Comment by ananyo2012** [comment]
Can you check your email. Sanchit sent an email earlier with the details of
speakers. You are tagged in that email as well
