### ISSUE TITLE
Show Workshop details modal on clicking Workshop title and Speaker details on clicking on speaker name

### ISSUE THREAD

**Issue by ananyo2012** [HydPy/hydpyconf2019#109]
When you click the name of a speaker in workshop a modal showing Speaker name, links and the Workshop detail shows up. We want to display speaker details on clicking on speaker name and a separate modal having the Workshop name and description on clicking the workshop title.

**Comment by ananyo2012** [comment]
@glebkema If you have time can you have a look at this issue ?

**Comment by glebkema** [comment]
I'm not yet sure about the time, unfortunately.

What information also needs to be changed? I think it will be a little strange if under the title of the workshop there will be someone's personal information without the name of this person.

**Comment by ananyo2012** [comment]
Didn't get your point. Name and description is already there. We just want
to move the link from the name to the Workshop title. So instead of
clicking the name the modal will open on clicking the Workshop title.

**Comment by ananyo2012** [comment]
@glebkema So I thought over on this and decided it would be best to keep the speaker details and workshop details in separate modals. That will make things clearer when an user clicks on the respective titles. Updated the issue description as well. Let me know if you will be able to work on this issue.

**Comment by glebkema** [comment]
After about 24 hours, I will think about what and when I can do, and I will write to you.

So far, some thoughts out loud:

If, by clicking on the spiker name, we show only info about the speaker, then it is necessary that for each speaker there should be some description. Are we able to provide this?

If, by clicking on the workshop title, we show only information about the workshop, then we need:
1) new layout for the workshop modal;
2) a set of fields about the workshop: name, description, leader and what else? a photo? time? a place?

If in the window about the workshop there is a link to the speaker, we will have to debug the interaction of the two modal windows. This is possible, but will complicate the development.

We can try to compose a modal window with information about both the speaker and the workshop, to show it on both links - from the title of the workshop and from the name of the speaker. But still, we need a new modal layout and a set of fields about the workshop.

**Comment by ananyo2012** [comment]
> If, by clicking on the spiker name, we show only info about the speaker, then it is necessary that for each speaker there should be some description. Are we able to provide this?

Yes we will put some description for each speaker. If no speaker data is available in yml file then show the name only without modal link
 
> If, by clicking on the workshop title, we show only information about the workshop, then we need:
> 
>     1. new layout for the workshop modal;
> 
>     2. a set of fields about the workshop: name, description, leader and what else? a photo? time? a place?

Let's keep it simple. Just use a simple bootstrap modal with Workshop title as the heading and show workshop description in content.

> We can try to compose a modal window with information about both the speaker and the workshop, to show it on both links - from the title of the workshop and from the name of the speaker. But still, we need a new modal layout and a set of fields about the workshop.

I think we will go with just workshop details and speaker details in separate modals. Not complicate things. If Workshop description is present link it to the modal else not. If speaker data is present link it to speaker modal else only show name without link.

**Comment by glebkema** [comment]
I understand the task as follows:
1) By clicking on the name of the workshop, show a modal window with information about the workshop.
2) By clicking on the name of the speaker, show a modal window with information about the speaker.
3) If no speaker data is available in yml file then show the speaker name only without modal link.

But I have not yet understood what a modal window for a workshop should look like. If we only change the name and description of the speaker to the name and description of the workshop, then the window will turn out to be something like this. It is unclear who the speaker is and what the words "Co-Founder" and the link to Linked-In refer to.

![modal-workshop](https://user-images.githubusercontent.com/3881568/69360923-baab5700-0c8b-11ea-8765-bb5ca33a1324.png)

What else needs to be changed?
What other data about workshops, in addition to names and descriptions, should be provided?

**Comment by ananyo2012** [comment]
You just need to put the name and description. So take the above picture and remove Speaker image, designation, company, social links. As simple as that. We will put the content and Agenda of the Workshop in the description section.

**Comment by glebkema** [comment]
Ah, I get it. Will do it on the weekend, ok?

**Comment by ananyo2012** [comment]
Yeah sure. Thanks a lot !
