### ISSUE TITLE
Update new logo of PyConf Hyderabad 2019

### ISSUE THREAD

**Issue by ananyo2012** [HydPy/hydpyconf2019#20]
@bhansa Creating this issue for the new logo. Please update when ready.

**Comment by subuhani** [comment]
![Pyconf-2019](https://user-images.githubusercontent.com/29629943/65335629-67ad1900-dbe2-11e9-9f0f-87af6cc6ccab.png)

@ananyo2012  updated the theme for this year PyConf.

**Comment by ananyo2012** [comment]
Looks good. @subuhani Can you try some pattern within the python logo keeping the theme intact ?

**Comment by inovizz** [comment]
A couple of suggestions @subuhani @bhansa @ananyo2012 

- If we are going with the same theme then can we give Hyderabad Touch to the Python logo? Reference - https://in.pycon.org/2018/img/banner-logo.png

- Can we think about changing the theme itself, How about changing "O" letter of PyConf with the Python logo and underneath Hyderabad as a text. Not sure how it would look but if you have time then please try.

**Comment by bhansa** [comment]
@subuhani Any updates on this?

**Comment by rmad17** [comment]
I think a similar theme was used in Pycon India 2016. Something new would be nicer.

**Comment by subuhani** [comment]
![PyConf-logo](https://user-images.githubusercontent.com/29629943/65749123-273e2580-e123-11e9-9c3b-154884753a41.jpg)

here is the finalized design!
