### ISSUE TITLE
Add favicon

### ISSUE THREAD

**Issue by bhansa** [HydPy/hydpyconf2019#26]
Create and add a favicon for the current website.

**Comment by bhansa** [comment]
I created this icon, let me know your thoughts.
![icon-512x512](https://user-images.githubusercontent.com/9723884/67311792-d650ff80-f51d-11e9-9ba8-804de9d4bf63.png)

**Comment by ananyo2012** [comment]
Yeah this looks great! It's in the PWA logo as well. Please go ahead and update!

**Comment by ananyo2012** [comment]
@bhansa Any update on this ?

**Comment by bhansa** [comment]
Yeah, sorry I didn't get a chance to look into it. Will be updating it soon.

**Comment by ananyo2012** [comment]
@bhansa I think you missed this :stuck_out_tongue:

**Comment by ananyo2012** [comment]
@bhansa You can update this along with the sponsor PR
