### ISSUE TITLE
Fix overlapping buttons in Mobile view

### ISSUE THREAD

**Issue by ananyo2012** [HydPy/hydpyconf2019#28]
Submit Talk and Get Tickets button are overlapping in mobile view.
![Screenshot from 2019-09-28 14-11-13](https://user-images.githubusercontent.com/10486343/65814055-b8340000-e1fa-11e9-8828-b1b66d54c770.png)

**Comment by vishalpolley** [comment]
Fixed overlapping of buttons in mobile view.
Please review #42
