### ISSUE TITLE
Improve SEO for Website

### ISSUE THREAD

**Issue by bhansa** [HydPy/hydpyconf2019#33]
Add meta tags, og attributes etc.
Enable indexing for search engines, use robots.txt

**Comment by ananyo2012** [comment]
I think we can still improve the SEO by adding xml Schema similar to this PR https://github.com/HydPy/hydpyconf2017/pull/36

**Comment by ananyo2012** [comment]
Searching for "PyConf Hyderabad" in google has the website listed 4th. Searching for "PyCon Hyderabad 2019" or "PyConf Hyderabad 2019" has the website in the very first rank. @inovizz @bhansa Should we changes the keywords and see if it comes at first for the first case ?

**Comment by bhansa** [comment]
![image](https://user-images.githubusercontent.com/9723884/67271805-eabed900-f4d8-11e9-9e2d-8c25f109b26c.png)
Good thing is that we are getting the navigation menu on search results.

![image](https://user-images.githubusercontent.com/9723884/67272539-61a8a180-f4da-11e9-86b8-3c3eef3b506d.png)
Event SEO as well.

**Comment by ananyo2012** [comment]
Yup the event pages are getting listed there. Townscript, Eventil, Tulula and Meetup. Let's close this in that case. Looks good for now.
