### ISSUE TITLE
Implement PWA features

### ISSUE THREAD

**Issue by bhansa** [HydPy/hydpyconf2019#34]
Implement PWA features to make the current website to have app-like features.
 - [x] Add web app manifest.
 - [x] Add a service worker.
 - [x] Make web app Installable

**Comment by ananyo2012** [comment]
@bhansa Will the 3rd point be useful? Since we don't have notifications as such to display.

**Comment by bhansa** [comment]
We can use notifications when certain events happens for example: Announcing important dates, announcing speakers, sponsors. 
We can also use it at the day of the event, to navigate people for the talks and schedule.

**Comment by ananyo2012** [comment]
Is that possible in a static website without any backend ? We need to create a service for sending the notifications right ? The PWA should be listening to the notification service and notify the user. That's the flow right ?

**Comment by bhansa** [comment]
Yes, correct. We can use firebase to send notifications and the service worker which we implement for app will be listening to firebase and display the notifications.

**Comment by ananyo2012** [comment]
Ok got it. This will be a interesting new feature. Some questions regarding
that. Are you familiar with working with firebase ? Also does firebase
requires any subscription cost ?

**Comment by bhansa** [comment]
Need to check on that. I think we will be able to use it through the HydPy google account without any cost.

Let's check on those details, till now I have only used this feature for personal purposes.

**Comment by ananyo2012** [comment]
@bhansa Should we split up this one into multiple issues and make it open for people to take up ?

**Comment by bhansa** [comment]
Sure, I'll create a separate issue for push notifications and somebody can take that up.

**Comment by ananyo2012** [comment]
@bhansa Does anything else needs to be done to make the app installable? I already see the "Add PyConf 2019 to Home Screen" in my Android device.

**Comment by bhansa** [comment]
Oh, great! I couldn't test that in my phone. I tested for desktop instead.

BTW, lighthouse report(without clear storage)

![image](https://user-images.githubusercontent.com/9723884/67362912-d4bd2100-f589-11e9-9562-e3081e37ea7c.png)
