### ISSUE TITLE
Change in faq.md

### ISSUE THREAD

**Issue by rachari** [HydPy/hydpyconf2019#37]
https://github.com/HydPy/hydpyconf2019/blob/master/faq.md

Shows Frequently added questions

Needs to be corrected to Frequently asked questions

**Comment by bhansa** [comment]
@rachari Anyway it should be fine, would you like to work on it?

**Comment by ananyo2012** [comment]
We also need to add FAQs. FAQs will be similar to https://in.pycon.org/2019/faq.html . For now we only need the ones in General Section.
