### ISSUE TITLE
Add Travel page

### ISSUE THREAD

**Issue by ananyo2012** [HydPy/hydpyconf2019#40]
Similar to https://in.pycon.org/2018/travel.html

**Comment by bhansa** [comment]
We have a venue details section on the homepage, it's commented as of now but we can use that once we add the details.

**Comment by ananyo2012** [comment]
Ah this is more like for those who are coming out of Hyderabad like stating the air, train, bus routes. Mani suggested created this page. @manitha Do we need this page since we will be already having the Venue section ?

**Comment by ananyo2012** [comment]
Let's go with https://in.pycon.org/2018/travel.html for detailed description. I really like the diagrams in this year's PyCon India website travel page https://in.pycon.org/2019/reaching-the-venues.html . If someone can design that, it would be a plus.

**Comment by aditya-prayaga** [comment]
Hi @ananyo2012  I can take this issue.
So My understanding is, there must be a "traveling to hyd" option in the drop-down has content of [https://in.pycon.org/2018/travel.html](https://in.pycon.org/2018/travel.html) and picture similar to [https://in.pycon.org/2019/reaching-the-venues.html](https://in.pycon.org/2019/reaching-the-venues.html) resembling hyd.

**Comment by ananyo2012** [comment]
Correct. You can go ahead with just the content first and add the images
later when you are done.

**Comment by aditya-prayaga** [comment]
Hey @ananyo2012, so there is only updating of the image(~ https://in.pycon.org/2019/reaching-the-venues.html ) left in the issue right?
If so I will pick another issue (or you could suggest one) and leave this to designers.

**Comment by ananyo2012** [comment]
Yeah please go ahead and pick up another open issue. I will update this
page later if needed

**Comment by ananyo2012** [comment]
Closing this since we have a Basic Travel Page with info. Will update it if needed.

**Comment by ananyo2012** [comment]
@all-contributors Add @aditya-369 for code
