### ISSUE TITLE
Display dynamic speaker description on speaker detail modal 

### ISSUE THREAD

**Issue by bhansa** [HydPy/hydpyconf2019#5]
There is a default modal for speaker description, we need to reuse it for all other descriptions as well.

**Comment by ananyo2012** [comment]
Is this dependent on #1 ?

**Comment by glebkema** [comment]
Hello, I'm ready to solve this issue. Just waiting for the next review on the #71 to check if I'm on the right way.

So please assign this issue to me, if you don't mind.

**Comment by ananyo2012** [comment]
@glebkema Assigned this one to you. Just left a review on the PR. Assigning you #61 as well.
