### ISSUE TITLE
Fix baseurl to work on both local environment and publish

### ISSUE THREAD

**Issue by bhansa** [HydPy/hydpyconf2019#6]
Reference file: `_config.yml`

**Comment by bhansa** [comment]
@ananyo2012 would you like to take this one?

**Comment by ananyo2012** [comment]
Hey Bharat. Sure. I will work on this over the weekend. I am planning to
get both year websites running from same server under /2017 and /2019 sub
domains.

**Comment by ananyo2012** [comment]
Deployed it to a digitalocean droplet which is live at http://157.245.100.145 . Changes to baseurl is a part of PR #7 . I need a heads up for this approach. Then I can go forward with setting up the domain and SSL setup. @HydPy/pyconf-2019 Any comments on this ?

**Comment by ananyo2012** [comment]
@HydPy/pyconf-2019 If we can go forward with this approach I can work on deployment scripts which can ease deployment to the server.

**Comment by ananyo2012** [comment]
Website live at https://pyconf.hydpy.org . Will create another issue for deployment script.
