### ISSUE TITLE
Add Keynote Speakers section

### ISSUE THREAD

**Issue by ananyo2012** [HydPy/hydpyconf2019#61]
We will be going to announce our first Keynote Speaker soon. Speaker section needs to be uncommented in `_layouts/default.html` and made ready for Keynote speaker announcement.

**Comment by ananyo2012** [comment]
@glebkema Ah I guess I can only assign the issue to someone who either has push access or has a PR for the same issue.

**Comment by glebkema** [comment]
@ananyo2012 Ok. I am working on this issue.
