### ISSUE TITLE
Remove menu movements when the modal opens

### ISSUE THREAD

**Issue by glebkema** [HydPy/hydpyconf2019#78]
![hydpyconf2019-header-jumping](https://user-images.githubusercontent.com/3881568/67889054-6c081280-fb4e-11e9-94ef-fd7341dad723.gif)

The menu and button in the header move left and right when the modal window opens and closes. 

At these moments, the scrollbar disappears and disappears, and the header adapts to the new width of free space. But it seems that the menus and buttons are reacting to this with a delay. They first bounce to the side, and then smoothly move to their original place.

**Comment by bhansa** [comment]
I believe this happens because of the bootstrap modal because it adds the overflow to the body, I have observed the same in multiple applications.

**Comment by glebkema** [comment]
I have found that the `.header` class has a property `transition (all 0.4s ease-in-out)` in the `_home.scss`.  This `all` is the reason of this effect because modal window changes the width of the `<body>`. When I commented on this property, the problem disappeared.

It is better to list in `transition` only those properties that are really necessary. For example: `transition (background-color 0.4s ease-in-out)`.

But perhaps the `transition` property itself is not needed for the `.header`. For what purpose was it added?

**Comment by glebkema** [comment]
I found this line of code already in the **init** commit.

![header-transition](https://user-images.githubusercontent.com/3881568/67946071-c2259600-fbe0-11e9-9194-afbea3bfc232.png)

I suggest to comment out the `transition` property for the `.header` for a while. And when we find out what CSS header properties should be "transitionable", we can uncomment this line and list the necessary properties instead of `all`.

What do you think about it?

**Comment by bhansa** [comment]
I agree with you @glebkema, replacing all with specific css props seems fine to me.
I think doing this will work, atleast we will not get that weird animation while opening the modal.
Just to add, the overflow will still be there and will change the size of the body because of the OOB bootstrap modal functionality.

Please go ahead with this change.
