### ISSUE TITLE
Remove T-hub as the workshop Venue

### ISSUE THREAD

**Issue by inovizz** [HydPy/hydpyconf2019#94]
Please get a PR ready for T-hub workshop venue removal and instead keep only one venue image for both Workshops and Conference.

**Comment by ananyo2012** [comment]
@bhansa Should we bring back the original venue design from https://themes.3rdwavemedia.com/demo/devconf/#venue-section We can accommodate the Travel details in modal as well. What do you think ?

**Comment by bhansa** [comment]
Yes, we can do that. We can link our venue details page as well for details.

**Comment by ananyo2012** [comment]
Ok. I will start work on this today.
